# Kiểu dữ liệu

In [86]:
import pandas as pd

In [87]:
df=pd.read_csv("bank.csv",delimiter=";")
df.head(5)

age          job  marital  education  balance housing loan   contact  day  \
0   30   unemployed  married    primary     1787      no   no  cellular   19   
1   33     services      NaN  secondary     4789     yes  yes  cellular   11   
2   35   management   single        NaN     1350     yes   no  cellular   16   
3   30   management  married   tertiary     1476     NaN  yes   unknown    3   
4   59  blue-collar  married  secondary        0     yes   no   unknown    5   

  month  
0   oct  
1   may  
2   apr  
3   jun  
4   may

+ age: Discrete. Vì kiểu số, có thể tính toán được, chứa các giá trị rời rạc
+ job: Norminal. Vì không tính toán được, cũng không có thứ tự
+ marital: Norminal. Vì không tính toán được, cũng không có thứ tự
+ education: Ordinal. Không phải kiểu số, có thư tự, trình độ học vấn -> có cấp bậc
+ balance: Continous. Vì kiểu số, có thể tính toán được, chứa các giá trị liên tục,
    miền giá trị của nó rải đều trên một trục số thực và không thể đếm được
+ housing: Norminal. Vì không tính toán được, cũng không có thứ tự
+ loan: Norminal. Vì không tính toán được, cũng không có thứ tự
+ contact: Norminal. Vì không tính toán được, cũng không có thứ tự
+ day: Norminal. Vì không tính toán được, mang tính định tính ko phải định lượng,
    cũng không có thứ tự
+ month: Norminal. Vì không tính toán được, mang tính định tính ko phải định lượng,
    cũng không có thứ tự

# Xử lý missing

In [88]:
df.isnull().sum()

age          0
job          1
marital      2
education    1
balance      0
housing      1
loan         0
contact      1
day          0
month        1
dtype: int64

Cần xử lý missing với các cột job, marital, education, housing, contact, month

In [89]:
from sklearn.impute import SimpleImputer
import numpy as np

In [90]:
# job
job_impute=SimpleImputer(np.nan,strategy="most_frequent")
X=df.values
X[:,1]=job_impute.fit_transform(X[:,1].reshape(-1,1)).ravel()
X

array([[30, 'unemployed', 'married', 'primary', 1787, 'no', 'no',
        'cellular', 19, 'oct'],
       [33, 'services', nan, 'secondary', 4789, 'yes', 'yes', 'cellular',
        11, 'may'],
       [35, 'management', 'single', nan, 1350, 'yes', 'no', 'cellular',
        16, 'apr'],
       [30, 'management', 'married', 'tertiary', 1476, nan, 'yes',
        'unknown', 3, 'jun'],
       [59, 'blue-collar', 'married', 'secondary', 0, 'yes', 'no',
        'unknown', 5, 'may'],
       [35, 'management', 'single', 'tertiary', 747, 'no', 'no',
        'cellular', 23, 'feb'],
       [36, 'self-employed', 'married', 'tertiary', 307, 'yes', 'no',
        'cellular', 14, 'may'],
       [39, 'technician', 'married', 'secondary', 147, 'yes', 'no',
        'cellular', 6, 'may'],
       [41, 'entrepreneur', 'married', 'tertiary', 221, 'yes', 'no',
        'unknown', 14, 'may'],
       [43, 'services', 'married', 'primary', -88, 'yes', 'yes',
        'cellular', 17, 'apr'],
       [39, 'services', 'ma

In [91]:
# marital      
marital_impute=SimpleImputer(np.nan,strategy="most_frequent")
X[:,2]=marital_impute.fit_transform(X[:,2].reshape(-1,1)).ravel()
X

array([[30, 'unemployed', 'married', 'primary', 1787, 'no', 'no',
        'cellular', 19, 'oct'],
       [33, 'services', 'married', 'secondary', 4789, 'yes', 'yes',
        'cellular', 11, 'may'],
       [35, 'management', 'single', nan, 1350, 'yes', 'no', 'cellular',
        16, 'apr'],
       [30, 'management', 'married', 'tertiary', 1476, nan, 'yes',
        'unknown', 3, 'jun'],
       [59, 'blue-collar', 'married', 'secondary', 0, 'yes', 'no',
        'unknown', 5, 'may'],
       [35, 'management', 'single', 'tertiary', 747, 'no', 'no',
        'cellular', 23, 'feb'],
       [36, 'self-employed', 'married', 'tertiary', 307, 'yes', 'no',
        'cellular', 14, 'may'],
       [39, 'technician', 'married', 'secondary', 147, 'yes', 'no',
        'cellular', 6, 'may'],
       [41, 'entrepreneur', 'married', 'tertiary', 221, 'yes', 'no',
        'unknown', 14, 'may'],
       [43, 'services', 'married', 'primary', -88, 'yes', 'yes',
        'cellular', 17, 'apr'],
       [39, 'services

In [92]:
# education
education_impute=SimpleImputer(np.nan,strategy="most_frequent")
X[:,3]=education_impute.fit_transform(X[:,3].reshape(-1,1)).ravel()
X

array([[30, 'unemployed', 'married', 'primary', 1787, 'no', 'no',
        'cellular', 19, 'oct'],
       [33, 'services', 'married', 'secondary', 4789, 'yes', 'yes',
        'cellular', 11, 'may'],
       [35, 'management', 'single', 'secondary', 1350, 'yes', 'no',
        'cellular', 16, 'apr'],
       [30, 'management', 'married', 'tertiary', 1476, nan, 'yes',
        'unknown', 3, 'jun'],
       [59, 'blue-collar', 'married', 'secondary', 0, 'yes', 'no',
        'unknown', 5, 'may'],
       [35, 'management', 'single', 'tertiary', 747, 'no', 'no',
        'cellular', 23, 'feb'],
       [36, 'self-employed', 'married', 'tertiary', 307, 'yes', 'no',
        'cellular', 14, 'may'],
       [39, 'technician', 'married', 'secondary', 147, 'yes', 'no',
        'cellular', 6, 'may'],
       [41, 'entrepreneur', 'married', 'tertiary', 221, 'yes', 'no',
        'unknown', 14, 'may'],
       [43, 'services', 'married', 'primary', -88, 'yes', 'yes',
        'cellular', 17, 'apr'],
       [39, '

In [93]:
# housing
housing_impute=SimpleImputer(np.nan,strategy="most_frequent")
X[:,5]=housing_impute.fit_transform(X[:,5].reshape(-1,1)).ravel()
X

array([[30, 'unemployed', 'married', 'primary', 1787, 'no', 'no',
        'cellular', 19, 'oct'],
       [33, 'services', 'married', 'secondary', 4789, 'yes', 'yes',
        'cellular', 11, 'may'],
       [35, 'management', 'single', 'secondary', 1350, 'yes', 'no',
        'cellular', 16, 'apr'],
       [30, 'management', 'married', 'tertiary', 1476, 'yes', 'yes',
        'unknown', 3, 'jun'],
       [59, 'blue-collar', 'married', 'secondary', 0, 'yes', 'no',
        'unknown', 5, 'may'],
       [35, 'management', 'single', 'tertiary', 747, 'no', 'no',
        'cellular', 23, 'feb'],
       [36, 'self-employed', 'married', 'tertiary', 307, 'yes', 'no',
        'cellular', 14, 'may'],
       [39, 'technician', 'married', 'secondary', 147, 'yes', 'no',
        'cellular', 6, 'may'],
       [41, 'entrepreneur', 'married', 'tertiary', 221, 'yes', 'no',
        'unknown', 14, 'may'],
       [43, 'services', 'married', 'primary', -88, 'yes', 'yes',
        'cellular', 17, 'apr'],
       [39,

In [94]:
# contact
contact_impute=SimpleImputer(np.nan,strategy="most_frequent")
X[:,-3]=contact_impute.fit_transform(X[:,-3].reshape(-1,1)).ravel()
X

array([[30, 'unemployed', 'married', 'primary', 1787, 'no', 'no',
        'cellular', 19, 'oct'],
       [33, 'services', 'married', 'secondary', 4789, 'yes', 'yes',
        'cellular', 11, 'may'],
       [35, 'management', 'single', 'secondary', 1350, 'yes', 'no',
        'cellular', 16, 'apr'],
       [30, 'management', 'married', 'tertiary', 1476, 'yes', 'yes',
        'unknown', 3, 'jun'],
       [59, 'blue-collar', 'married', 'secondary', 0, 'yes', 'no',
        'unknown', 5, 'may'],
       [35, 'management', 'single', 'tertiary', 747, 'no', 'no',
        'cellular', 23, 'feb'],
       [36, 'self-employed', 'married', 'tertiary', 307, 'yes', 'no',
        'cellular', 14, 'may'],
       [39, 'technician', 'married', 'secondary', 147, 'yes', 'no',
        'cellular', 6, 'may'],
       [41, 'entrepreneur', 'married', 'tertiary', 221, 'yes', 'no',
        'unknown', 14, 'may'],
       [43, 'services', 'married', 'primary', -88, 'yes', 'yes',
        'cellular', 17, 'apr'],
       [39,

In [95]:
# month
contact_impute=SimpleImputer(np.nan,strategy="most_frequent")
X[:,-1]=contact_impute.fit_transform(X[:,-1].reshape(-1,1)).ravel()
X

array([[30, 'unemployed', 'married', 'primary', 1787, 'no', 'no',
        'cellular', 19, 'oct'],
       [33, 'services', 'married', 'secondary', 4789, 'yes', 'yes',
        'cellular', 11, 'may'],
       [35, 'management', 'single', 'secondary', 1350, 'yes', 'no',
        'cellular', 16, 'apr'],
       [30, 'management', 'married', 'tertiary', 1476, 'yes', 'yes',
        'unknown', 3, 'jun'],
       [59, 'blue-collar', 'married', 'secondary', 0, 'yes', 'no',
        'unknown', 5, 'may'],
       [35, 'management', 'single', 'tertiary', 747, 'no', 'no',
        'cellular', 23, 'feb'],
       [36, 'self-employed', 'married', 'tertiary', 307, 'yes', 'no',
        'cellular', 14, 'may'],
       [39, 'technician', 'married', 'secondary', 147, 'yes', 'no',
        'cellular', 6, 'may'],
       [41, 'entrepreneur', 'married', 'tertiary', 221, 'yes', 'no',
        'unknown', 14, 'may'],
       [43, 'services', 'married', 'primary', -88, 'yes', 'yes',
        'cellular', 17, 'apr'],
       [39,

# Mã hóa dữ liệu

In [96]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [97]:
X[:,2]

array(['married', 'married', 'single', 'married', 'married', 'single',
       'married', 'married', 'married', 'married', 'married', 'married',
       'married', 'single', 'married', 'married', 'married', 'married',
       'single'], dtype=object)

In [98]:
# marital
marital_label_encoder= LabelEncoder()
X[:,2]=marital_label_encoder.fit_transform(X[:,2])
X

array([[30, 'unemployed', 0, 'primary', 1787, 'no', 'no', 'cellular', 19,
        'oct'],
       [33, 'services', 0, 'secondary', 4789, 'yes', 'yes', 'cellular',
        11, 'may'],
       [35, 'management', 1, 'secondary', 1350, 'yes', 'no', 'cellular',
        16, 'apr'],
       [30, 'management', 0, 'tertiary', 1476, 'yes', 'yes', 'unknown',
        3, 'jun'],
       [59, 'blue-collar', 0, 'secondary', 0, 'yes', 'no', 'unknown', 5,
        'may'],
       [35, 'management', 1, 'tertiary', 747, 'no', 'no', 'cellular', 23,
        'feb'],
       [36, 'self-employed', 0, 'tertiary', 307, 'yes', 'no', 'cellular',
        14, 'may'],
       [39, 'technician', 0, 'secondary', 147, 'yes', 'no', 'cellular',
        6, 'may'],
       [41, 'entrepreneur', 0, 'tertiary', 221, 'yes', 'no', 'unknown',
        14, 'may'],
       [43, 'services', 0, 'primary', -88, 'yes', 'yes', 'cellular', 17,
        'apr'],
       [39, 'services', 0, 'secondary', 9374, 'yes', 'no', 'unknown', 20,
        'may'],

In [99]:
# housing
housing_label_encoder= LabelEncoder()
X[:,5]=housing_label_encoder.fit_transform(X[:,5])
X

array([[30, 'unemployed', 0, 'primary', 1787, 0, 'no', 'cellular', 19,
        'oct'],
       [33, 'services', 0, 'secondary', 4789, 1, 'yes', 'cellular', 11,
        'may'],
       [35, 'management', 1, 'secondary', 1350, 1, 'no', 'cellular', 16,
        'apr'],
       [30, 'management', 0, 'tertiary', 1476, 1, 'yes', 'unknown', 3,
        'jun'],
       [59, 'blue-collar', 0, 'secondary', 0, 1, 'no', 'unknown', 5,
        'may'],
       [35, 'management', 1, 'tertiary', 747, 0, 'no', 'cellular', 23,
        'feb'],
       [36, 'self-employed', 0, 'tertiary', 307, 1, 'no', 'cellular', 14,
        'may'],
       [39, 'technician', 0, 'secondary', 147, 1, 'no', 'cellular', 6,
        'may'],
       [41, 'entrepreneur', 0, 'tertiary', 221, 1, 'no', 'unknown', 14,
        'may'],
       [43, 'services', 0, 'primary', -88, 1, 'yes', 'cellular', 17,
        'apr'],
       [39, 'services', 0, 'secondary', 9374, 1, 'no', 'unknown', 20,
        'may'],
       [43, 'admin.', 0, 'secondary', 264

In [100]:
# loan
loan_label_encoder= LabelEncoder()
X[:,6]=loan_label_encoder.fit_transform(X[:,6])
X

array([[30, 'unemployed', 0, 'primary', 1787, 0, 0, 'cellular', 19,
        'oct'],
       [33, 'services', 0, 'secondary', 4789, 1, 1, 'cellular', 11,
        'may'],
       [35, 'management', 1, 'secondary', 1350, 1, 0, 'cellular', 16,
        'apr'],
       [30, 'management', 0, 'tertiary', 1476, 1, 1, 'unknown', 3, 'jun'],
       [59, 'blue-collar', 0, 'secondary', 0, 1, 0, 'unknown', 5, 'may'],
       [35, 'management', 1, 'tertiary', 747, 0, 0, 'cellular', 23,
        'feb'],
       [36, 'self-employed', 0, 'tertiary', 307, 1, 0, 'cellular', 14,
        'may'],
       [39, 'technician', 0, 'secondary', 147, 1, 0, 'cellular', 6,
        'may'],
       [41, 'entrepreneur', 0, 'tertiary', 221, 1, 0, 'unknown', 14,
        'may'],
       [43, 'services', 0, 'primary', -88, 1, 1, 'cellular', 17, 'apr'],
       [39, 'services', 0, 'secondary', 9374, 1, 0, 'unknown', 20, 'may'],
       [43, 'admin.', 0, 'secondary', 264, 1, 0, 'cellular', 17, 'apr'],
       [36, 'technician', 0, 'tertia

In [101]:
# job
job_onehot = OneHotEncoder()
temp=job_onehot.fit_transform(X[:,1].reshape(-1,1)).toarray()
X=np.concatenate((X,temp),axis=1)
X=np.delete(X,1,axis=1)
X

array([[30, 0, 'primary', 1787, 0, 0, 'cellular', 19, 'oct', 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
       [33, 0, 'secondary', 4789, 1, 1, 'cellular', 11, 'may', 0.0, 0.0,
        0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
       [35, 1, 'secondary', 1350, 1, 0, 'cellular', 16, 'apr', 0.0, 0.0,
        0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [30, 0, 'tertiary', 1476, 1, 1, 'unknown', 3, 'jun', 0.0, 0.0,
        0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [59, 0, 'secondary', 0, 1, 0, 'unknown', 5, 'may', 0.0, 1.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [35, 1, 'tertiary', 747, 0, 0, 'cellular', 23, 'feb', 0.0, 0.0,
        0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [36, 0, 'tertiary', 307, 1, 0, 'cellular', 14, 'may', 0.0, 0.0,
        0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
       [39, 0, 'secondary', 147, 1, 0, 'cellular', 6, 'may', 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
       [41, 0, 'tertiary', 221, 1, 0, 'unknown', 14, 'may', 0.0, 0.0,
        1.

In [102]:
# education, 2 vì đã xóa cột job
education_label_encoder= LabelEncoder()
X[:,2]=education_label_encoder.fit_transform(X[:,2])
X

array([[30, 0, 0, 1787, 0, 0, 'cellular', 19, 'oct', 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 1.0],
       [33, 0, 1, 4789, 1, 1, 'cellular', 11, 'may', 0.0, 0.0, 0.0, 0.0,
        0.0, 1.0, 0.0, 0.0, 0.0],
       [35, 1, 1, 1350, 1, 0, 'cellular', 16, 'apr', 0.0, 0.0, 0.0, 1.0,
        0.0, 0.0, 0.0, 0.0, 0.0],
       [30, 0, 2, 1476, 1, 1, 'unknown', 3, 'jun', 0.0, 0.0, 0.0, 1.0,
        0.0, 0.0, 0.0, 0.0, 0.0],
       [59, 0, 1, 0, 1, 0, 'unknown', 5, 'may', 0.0, 1.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0],
       [35, 1, 2, 747, 0, 0, 'cellular', 23, 'feb', 0.0, 0.0, 0.0, 1.0,
        0.0, 0.0, 0.0, 0.0, 0.0],
       [36, 0, 2, 307, 1, 0, 'cellular', 14, 'may', 0.0, 0.0, 0.0, 0.0,
        1.0, 0.0, 0.0, 0.0, 0.0],
       [39, 0, 1, 147, 1, 0, 'cellular', 6, 'may', 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 1.0, 0.0],
       [41, 0, 2, 221, 1, 0, 'unknown', 14, 'may', 0.0, 0.0, 1.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0],
       [43, 0, 0, -88, 1, 1, 'cellular', 17, 'apr'

In [103]:
# contact, vị trí là 6 vì đã xóa cột job
contact_onehot = OneHotEncoder()
temp=contact_onehot.fit_transform(X[:,6].reshape(-1,1)).toarray()
X=np.concatenate((X,temp),axis=1)
X=np.delete(X,6,axis=1)
X

array([[30, 0, 0, 1787, 0, 0, 19, 'oct', 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 1.0, 1.0, 0.0],
       [33, 0, 1, 4789, 1, 1, 11, 'may', 0.0, 0.0, 0.0, 0.0, 0.0, 1.0,
        0.0, 0.0, 0.0, 1.0, 0.0],
       [35, 1, 1, 1350, 1, 0, 16, 'apr', 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 1.0, 0.0],
       [30, 0, 2, 1476, 1, 1, 3, 'jun', 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 1.0],
       [59, 0, 1, 0, 1, 0, 5, 'may', 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 1.0],
       [35, 1, 2, 747, 0, 0, 23, 'feb', 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 1.0, 0.0],
       [36, 0, 2, 307, 1, 0, 14, 'may', 0.0, 0.0, 0.0, 0.0, 1.0, 0.0,
        0.0, 0.0, 0.0, 1.0, 0.0],
       [39, 0, 1, 147, 1, 0, 6, 'may', 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        1.0, 0.0, 1.0, 0.0],
       [41, 0, 2, 221, 1, 0, 14, 'may', 0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 1.0],
       [43, 0, 0, -88, 1, 1, 17, 'apr', 0.0, 0.0, 0.0, 0.0, 0.0, 