# Kiểu dữ liệu

In [65]:
import pandas as pd

In [66]:
df=pd.read_csv("titanic.csv")
df.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

+ Survived: Norminal. Vì không tính toán được, cũng không có thứ tự
+ PClass: Norminal. Vì không tính toán được, cũng không có thứ tự (vì có nhiều tiêu chí để xét thứ tự)
+ Name: Norminal. Vì không tính toán được, cũng không có thứ tự
+ Sex: Norminal. Vì không tính toán được, cũng không có thứ tự
+ Age: Discrete. Vì kiểu số, có thể tính toán được, chứa các giá trị rời rạc
+ Ticket: Norminal. Vì không tính toán được, cũng không có thứ tự
+ Fare: Continous. Vì kiểu số, có thể tính toán được, chứa các giá trị liên tục, miền giá trị của nó rải đều trên một trục số thực và không thể đếm được
+ Cabin: Norminal. Vì không tính toán được, cũng không có thứ tự
+ Embarket: Norminal. Vì không tính toán được, cũng không có thứ tự

    

# Xử lý missing

In [67]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Ở đây xử lý 3 cột bị thiếu dữ liệu là Age, Cabin, Embarked

In [68]:
from sklearn.impute import SimpleImputer
import numpy as np

In [69]:
# Age
age_impute=SimpleImputer(np.nan,strategy="mean")
X=df.values
X[:,5]=age_impute.fit_transform(X[:,5].reshape(-1,1)).ravel()
X


array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, nan, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, nan, 'Q']], dtype=object)

In [70]:
# Cabin
cabin_impute=SimpleImputer(np.nan,strategy="most_frequent")
X[:,-2]=cabin_impute.fit_transform(X[:,-2].reshape(-1,1)).ravel()
X

array([[1, 0, 3, ..., 7.25, 'B96 B98', 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, 'B96 B98', 'S'],
       ...,
       [889, 0, 3, ..., 23.45, 'B96 B98', 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, 'B96 B98', 'Q']], dtype=object)

In [71]:
# Embarked
embarked_impute=SimpleImputer(np.nan,strategy="most_frequent")
X[:,-1]=embarked_impute.fit_transform(X[:,-1].reshape(-1,1)).ravel()
X

array([[1, 0, 3, ..., 7.25, 'B96 B98', 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, 'B96 B98', 'S'],
       ...,
       [889, 0, 3, ..., 23.45, 'B96 B98', 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, 'B96 B98', 'Q']], dtype=object)

# Mã hóa dữ liệu

In [72]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [73]:
X[:,4]

array(['male', 'female', 'female', 'female', 'male', 'male', 'male',
       'male', 'female', 'female', 'female', 'female', 'male', 'male',
       'female', 'female', 'male', 'male', 'female', 'female', 'male',
       'male', 'female', 'male', 'female', 'female', 'male', 'male',
       'female', 'male', 'male', 'female', 'female', 'male', 'male',
       'male', 'male', 'male', 'female', 'female', 'female', 'female',
       'male', 'female', 'female', 'male', 'male', 'female', 'male',
       'female', 'male', 'male', 'female', 'female', 'male', 'male',
       'female', 'male', 'female', 'male', 'male', 'female', 'male',
       'male', 'male', 'male', 'female', 'male', 'female', 'male', 'male',
       'female', 'male', 'male', 'male', 'male', 'male', 'male', 'male',
       'female', 'male', 'male', 'female', 'male', 'female', 'female',
       'male', 'male', 'female', 'male', 'male', 'male', 'male', 'male',
       'male', 'male', 'male', 'male', 'female', 'male', 'female', 'male',
      

In [62]:
# Sex
sex_label_encoder= LabelEncoder()
X[:,4]=sex_label_encoder.fit_transform(X[:,4])
X

array([[1, 0, 3, ..., 7.25, 'B96 B98', 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, 'B96 B98', 'S'],
       ...,
       [889, 0, 3, ..., 23.45, 'B96 B98', 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, 'B96 B98', 'Q']], dtype=object)

In [63]:
# Embarket
embarket_onehot = OneHotEncoder()
temp=embarket_onehot.fit_transform(X[:,-1].reshape(-1,1)).toarray()
X=np.concatenate((X,temp),axis=1)
#X=np.delete(X,3,axis=1)
X

array([[1, 0, 3, ..., 0.0, 0.0, 1.0],
       [2, 1, 1, ..., 1.0, 0.0, 0.0],
       [3, 1, 3, ..., 0.0, 0.0, 1.0],
       ...,
       [889, 0, 3, ..., 0.0, 0.0, 1.0],
       [890, 1, 1, ..., 1.0, 0.0, 0.0],
       [891, 0, 3, ..., 0.0, 1.0, 0.0]], dtype=object)